name: Terragrunt Preview

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  preview:
    name: Plan Terragrunt changes in changed stacks
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      ### Create Pull Request comment

      - name: Prepare pull request preview comment
        if: github.event.pull_request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: preview
          message: |
            ## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}

            :warning: preview is being created... please stand by!

      ### Check out the code

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      ### Install tooling

      - name: Install Terramate
        uses: terramate-io/terramate-action@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Terraform and Terragrunt with asdf
        run: |
          asdf plugin add terraform
          asdf plugin add terragrunt
          asdf install terraform
          asdf install terragrunt

      ### Linting

      - name: Check Terramate formatting
        run: terramate fmt --check

      - name: Check Terraform formatting
        run: terragrunt hclfmt --terragrunt-check

      ### Check for changed stacks

      - name: List changed stacks
        id: list-changed
        run: terramate list --changed

      ### Configure cloud credentials

      - name: 'Configure Azure credentials'
        if: steps.list-changed.outputs.stdout
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
          
      - name: Verify Azure credentials
        if: steps.list-changed.outputs.stdout
        run: |
          az account show

      ### Run the Terraform preview via Terramate in each changed stack

      - name: Initialize Terragrunt in changed stacks
        if: steps.list-changed.outputs.stdout
        run: terramate run --parallel 1 --changed -- terragrunt init -lock-timeout=5m
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Plan Terragrunt changes in changed stacks
        if: steps.list-changed.outputs.stdout
        id: tgplan
        run: |
          terramate run \
            --parallel 5 \
            --changed \
            --continue-on-error \
            -- \
            terragrunt plan -out $(pwd)/out.tfplan \
            -lock=false
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

      ### Update Pull Request comment

      - name: Generate preview details
        if: steps.list-changed.outputs.stdout
        id: comment
        run: |
          echo >>pr-comment.txt "## Preview of Terragrunt changes in ${{ github.event.pull_request.head.sha }}"
          echo >>pr-comment.txt
          echo >>pr-comment.txt "[:mag: View Details on Terramate Cloud]($(cat prod/preview_url.txt))"
          echo >>pr-comment.txt
          echo >>pr-comment.txt "### Changed Stacks"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```bash'
          echo >>pr-comment.txt "${{ steps.list-changed.outputs.stdout }}"
          echo >>pr-comment.txt '```'
          echo >>pr-comment.txt
          echo >>pr-comment.txt "#### Terragrunt Plan"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```terraform'
          terramate run \
            --changed \
            --terragrunt \
            -- \
            terragrunt show -no-color out.tfplan \
            |& dd bs=1024 count=248 >>pr-comment.txt
          [ "${PIPESTATUS[0]}" == "141" ] && sed -i 's/#### Terragrunt Plan/#### :warning: Terragrunt Plan truncated: please check console output :warning:/' pr-comment.txt
          echo >>pr-comment.txt '```'
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      # - name: Generate preview when no stacks changed
      #   if: success() && !steps.list-changed.outputs.stdout
      #   run: |
      #     echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
      #     echo >>pr-comment.txt
      #     echo >>pr-comment.txt "### Changed Stacks"
      #     echo >>pr-comment.txt
      #     echo >>pr-comment.txt 'No changed stacks, no detailed preview will be generated.'
      #     cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      # - name: Generate preview when things failed
      #   if: failure()
      #   run: |
      #     echo >>pr-comment.txt "## Preview of Terraform changes in ${{ github.event.pull_request.head.sha }}"
      #     echo >>pr-comment.txt
      #     echo >>pr-comment.txt '> [!TIP]'
      #     echo >>pr-comment.txt '> [:mag: View all Preview Details on Terramate Cloud](https://cloud.terramate.io/o/terramate-demo/review-requests)'
      #     echo >>pr-comment.txt
      #     echo >>pr-comment.txt "### Changed Stacks"
      #     echo >>pr-comment.txt
      #     echo >>pr-comment.txt '```bash'
      #     echo >>pr-comment.txt "${{ steps.list-changed.outputs.stdout }}"
      #     echo >>pr-comment.txt '```'
      #     echo >>pr-comment.txt ':boom: Generating preview failed. Please see details in Actions output.'
      #     cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      # - name: Publish generated preview as GitHub commnent
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     header: preview
      #     path: pr-comment.txt